spring:
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile
  h2:
    console:
      enabled: true
      path: /h2-console # H2 콘솔에 접근할 경로
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  issuer: rexlam@naver.com
  secret_key: study-springboot