spring:
  h2:
    console:
      enabled: true
      path: /h2-console # H2 콘솔에 접근할 경로
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

jwt:
  issuer: rexlam@naver.com
  secret_key: study-springboot