spring:
  jpa:
#    전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
