INSERT INTO ARTICLE (TITLE, CONTENT, CREATED_AT, UPDATED_AT) VALUES ('제목1', '내용1', NOW(), NOW());
INSERT INTO ARTICLE (TITLE, CONTENT, CREATED_AT, UPDATED_AT) VALUES ('제목2', '내용2', NOW(), NOW());
INSERT INTO ARTICLE (TITLE, CONTENT, CREATED_AT, UPDATED_AT) VALUES ('제목3', '내용3', NOW(), NOW());